name: BankCloud CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Seleccione el ambiente"
        required: true
        default: DEV
        type: choice
        options:
          - DEV
          - QA
          - PROD

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:

  # ==========================================================
  # CI - CONTINUOUS INTEGRATION
  # ==========================================================

  ci:
    name: CI - Build, Scan and Push
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    steps:

      # ------------------------------------------------------
      # 1. Checkout
      # ------------------------------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false


      # ------------------------------------------------------
      # 2. AWS Credentials
      # ------------------------------------------------------

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # ------------------------------------------------------
      # 3. Login Amazon ECR
      # ------------------------------------------------------

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # ------------------------------------------------------
      # 4. Docker Build - Frontend
      # ------------------------------------------------------

      - name: Docker Build - Frontend
        run: |
          docker build \
            -t bankcloud/frontend:${{ github.sha }} \
            ./bankcloud-app/frontend


      # ------------------------------------------------------
      # 5. Docker Build - ProductCatalogService
      # ------------------------------------------------------

      - name: Docker Build - ProductCatalogService
        run: |
          docker build \
            -t bankcloud/productcatalogservice:${{ github.sha }} \
            ./bankcloud-app/productcatalogservice


      # ------------------------------------------------------
      # 6. Security Scan - Frontend
      # ------------------------------------------------------

      - name: Trivy Scan - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bankcloud/frontend:${{ github.sha }}
          format: table
          exit-code: "1"
          severity: "CRITICAL,HIGH"


      # ------------------------------------------------------
      # 7. Security Scan - ProductCatalogService
      # ------------------------------------------------------

      - name: Trivy Scan - ProductCatalogService
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bankcloud/productcatalogservice:${{ github.sha }}
          format: table
          exit-code: "1"
          severity: "CRITICAL,HIGH"


      # ------------------------------------------------------
      # 8. Tag + Push Frontend → ECR
      # ------------------------------------------------------

      - name: Push Frontend to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag \
            bankcloud/frontend:${{ github.sha }} \
            $ECR_REGISTRY/bankcloud/frontend:${{ github.sha }}

          docker push \
            $ECR_REGISTRY/bankcloud/frontend:${{ github.sha }}


      # ------------------------------------------------------
      # 9. Tag + Push ProductCatalogService → ECR
      # ------------------------------------------------------

      - name: Push ProductCatalogService to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag \
            bankcloud/productcatalogservice:${{ github.sha }} \
            $ECR_REGISTRY/bankcloud/productcatalogservice:${{ github.sha }}

          docker push \
            $ECR_REGISTRY/bankcloud/productcatalogservice:${{ github.sha }}


  # ==========================================================
  # CD - TERRAFORM / INFRASTRUCTURE
  # ==========================================================

  terraform:
    name: CD - Terraform - ${{ github.event.inputs.environment }}

    runs-on: ubuntu-latest

    # Terraform solo se ejecuta si CI termina correctamente
    needs: ci

    environment:
      name: ${{ github.event.inputs.environment }}

    defaults:
      run:
        shell: bash

    steps:

      # ------------------------------------------------------
      # 10. Checkout
      # ------------------------------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false


      # ------------------------------------------------------
      # 11. Seleccionar ambiente Terraform
      # ------------------------------------------------------

      - name: Seleccionar directorio Terraform
        run: |
          if [ "${{ github.event.inputs.environment }}" = "DEV" ]; then

            echo "TF_DIR=terraform/environments/dev" >> "$GITHUB_ENV"

          elif [ "${{ github.event.inputs.environment }}" = "QA" ]; then

            echo "TF_DIR=terraform/environments/qa" >> "$GITHUB_ENV"

          elif [ "${{ github.event.inputs.environment }}" = "PROD" ]; then

            echo "TF_DIR=terraform/environments/prod" >> "$GITHUB_ENV"

          else

            echo "Ambiente no válido"
            exit 1

          fi


      # ------------------------------------------------------
      # 12. Información del despliegue
      # ------------------------------------------------------

      - name: Mostrar ambiente
        run: |
          echo "========================================"
          echo "Proyecto: BankCloud"
          echo "Ambiente: ${{ github.event.inputs.environment }}"
          echo "Directorio Terraform: $TF_DIR"
          echo "Commit: ${{ github.sha }}"
          echo "========================================"


      # ------------------------------------------------------
      # 13. AWS Credentials
      # ------------------------------------------------------

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # ------------------------------------------------------
      # 14. Setup Terraform
      # ------------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8


      # ------------------------------------------------------
      # 15. Terraform Init
      # ------------------------------------------------------

      - name: Terraform Init
        run: |
          terraform -chdir=$TF_DIR init -input=false


      # ------------------------------------------------------
      # 16. Terraform Format
      # ------------------------------------------------------

      - name: Terraform Format
        run: |
          terraform -chdir=$TF_DIR fmt -check -recursive


      # ------------------------------------------------------
      # 17. Terraform Validate
      # ------------------------------------------------------

      - name: Terraform Validate
        run: |
          terraform -chdir=$TF_DIR validate


      # ------------------------------------------------------
      # 18. Terraform Plan
      # ------------------------------------------------------

      - name: Terraform Plan
        run: |
          terraform -chdir=$TF_DIR plan \
            -input=false \
            -lock-timeout=5m \
            -out=tfplan


      # ------------------------------------------------------
      # 19. Terraform Apply
      # ------------------------------------------------------

      - name: Terraform Apply
        run: |
          terraform -chdir=$TF_DIR apply \
            -input=false \
            -auto-approve \
            tfplan


      # ------------------------------------------------------
      # 20. Resultado
      # ------------------------------------------------------

      - name: Deployment Completed
        run: |
          echo "========================================"
          echo "CI/CD COMPLETADO"
          echo "Proyecto: BankCloud"
          echo "Ambiente: ${{ github.event.inputs.environment }}"
          echo "Commit: ${{ github.sha }}"
          echo "========================================"